service: doorbell-app

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    environment:
        CALLS_TABLE: ${self:service}-calls-${self:provider.stage}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CALLS_TABLE}"
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource:
              - Fn::Join:
                    - ":"
                    - - arn:aws:secretsmanager
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - secret:*

functions:
    answercall:
        handler: dist/answercall.handler
        events:
            - http:
                  path: answercall
                  method: GET
                  cors: true
            - http:
                  path: answercall
                  method: POST
                  cors: true
    acceptRecording:
        handler: dist/acceptRecording.handler
        events:
            - http:
                  path: acceptRecording
                  method: POST
                  cors: true
    acceptTranscript:
        handler: dist/acceptTranscript.handler
        events:
            - http:
                  path: acceptTranscript
                  method: POST
                  cors: true
    handleSMSReply:
        handler: dist/handleSMSReply.handler
        events:
            - http:
                  path: handleSMSReply
                  method: POST
                  cors: true

resources:
    Resources:
        CallsTable:
            Type: "AWS::DynamoDB::Table"
            Properties:
                AttributeDefinitions:
                    - AttributeName: phone_number
                      AttributeType: S
                KeySchema:
                    - AttributeName: phone_number
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:provider.environment.CALLS_TABLE}
