service: doorbell-app

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    environment:
        PHONE_NUMBER: "+12055258990"
    iamRoleStatements:

functions:
    answercall:
        handler: dist/answercall.handler
        events:
            - http:
                  path: answercall
                  method: GET
                  cors: true
            - http:
                  path: answercall
                  method: POST
                  cors: true
    acceptRecording:
        handler: dist/acceptRecording.handler
        events:
            - http:
                  path: acceptRecording
                  method: POST
                  cors: true
    acceptTranscript:
        handler: dist/acceptTranscript.handler
        events:
            - http:
                  path: acceptTranscript
                  method: POST
                  cors: true

resources:
